name: Deploy to GitHub Pages

on:
  push:
    branches: [master, main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Create dist directory
        run: mkdir -p dist
        
      - name: Copy files to dist
        run: |
          cp index.html dist/
          cp public/manifest.json dist/
          cp public/favicon.ico dist/
          cp public/*.png dist/ 2>/dev/null || true
          cp base45-lib.js dist/ 2>/dev/null || true
          cp sdp-compact.js dist/ 2>/dev/null || true
          cp binary-codec.js dist/ 2>/dev/null || true
          cp asn1-uper-codec.js dist/ 2>/dev/null || true
          cp version.js dist/ 2>/dev/null || true
          cp crc.js dist/ 2>/dev/null || true
          cp update-version.js dist/ 2>/dev/null || true
          
      - name: Update version info
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          sed -i "s/GIT_COMMIT = '[^']*'/GIT_COMMIT = '$SHORT_SHA'/" dist/index.html
          echo "Updated commit hash to $SHORT_SHA"
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4