name: Deploy to GitHub Pages

on:
  push:
    branches: [master, main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for GitVersion
        
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
      
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
      
      - name: Display version
        run: |
          echo "Version: ${{ steps.gitversion.outputs.semVer }}"
          echo "FullVersion: ${{ steps.gitversion.outputs.fullSemVer }}"
          echo "ShortSha: ${{ steps.gitversion.outputs.shortSha }}"
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Update version files
        run: |
          # Update package.json
          npm version ${{ steps.gitversion.outputs.semVer }} --no-git-tag-version --allow-same-version
          
          # Update version.js with static build date
          BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          cat > version.js << EOF
          // Centralized version configuration
          export const VERSION = '${{ steps.gitversion.outputs.semVer }}';
          export const BUILD_DATE = '${BUILD_DATE}'; // Updated by CI/CD
          export const GIT_COMMIT = '${{ steps.gitversion.outputs.shortSha }}'; // Updated by CI/CD
          
          // Version string for cache busting
          export const CACHE_VERSION = VERSION;
          EOF
          
          # Update sw.js cache version
          sed -i "s/const CACHE_VERSION = '[^']*'/const CACHE_VERSION = '${{ steps.gitversion.outputs.semVer }}'/" sw.js
          
          # Update index.html meta tag
          sed -i 's/<meta name="version" content="[^"]*"/<meta name="version" content="${{ steps.gitversion.outputs.semVer }}"/' index.html
          
      - name: Build with cache busting
        env:
          VERSION: ${{ steps.gitversion.outputs.semVer }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          node build-with-cache-bust.js
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4